apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: nada
  labels:
    team: nada
spec:
  image: {{image}}
  port: 8000
  accessPolicy:
    outbound:
      rules:
        - application: dakan-api-les-ekstern
          namespace: dataplattform
        - application: begreps-api
          namespace: teamdatajegerne
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 70
  liveness:
    path: /digdir-api/isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /digdir-api/isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  env:
    - name: PUBLISHER
      value: "https://data.brreg.no/enhetsregisteret/api/enheter/889640782"
    - name: CATALOG_HOMEPAGE
      value: "https://data.nav.no"
    - name: NAV_API_PORTAL
      value: "https://api-portal.nav.no/"
    - name: COLLECTION_IDENTIFIER
      value: {{collection_identifier}}
    - name: COLLECTION_PUBLISHER
      value: {{collection_publisher}}
    - name: TERM_COLLECTION_NAME
      value: {{term_collection_name}}
    - name: TERM_CONCEPT_IDENTIFIER
      value: {{term_concept_identifier}}
    - name: TERM_CONCEPT_CONTACT
      value: {{term_concept_contact}}
    - name: TERM_CONCEPT_TYPE
      value: {{term_concept_type}}
    - name: API_COLLECTION_NAME
      value: {{api_collection_name}}
    - name: API_CONCEPT_IDENTIFIER
      value: {{api_concept_identifier}}
    - name: API_CONCEPT_TYPE
      value: {{api_concept_type}}
    - name: ES_INDEX_ENDPOINT
      value: "http://dakan-api-les-ekstern.dataplattform/api/dcat"
    - name: BUCKET_ENDPOINT
      value: {{bucket_endpoint}}
    - name: CERT_PATH
      value: {{cert_path}}
    - name: REQUESTS_CA_BUNDLE
      value: {{cert_path}}
    - name: PRODUCTION
      value: "true"
    - name: ES_INDEX_ENDPOINT_TERMS
      value: "http://begreps-api.teamdatajegerne/api/dcat"
  ingresses:
    - {{ingress}}
  leaderElection: false
  prometheus:
    enabled: true
    path: /digdir-api/metrics
