API_JSON = {"hits": {"hits": [{'_index': 'odata_v5',
                               '_type': '_doc',
                               '_id': 'API.Arbeidsplassen',
                               '_version': 6,
                               'found': True,
                               '_source': {'id': 'API.Arbeidsplassen',
                                           'type': 'api',
                                           'suggest': 'Arbeidsplassen',
                                           'description': 'Stillingssøk på Arbeidsplassen inneholder en oversikt over de fleste aktive ledige stillinger. Stillingssøket inneholder både stillinger som er registrert direkte hos NAV samt hentet inn fra en rekke nettsteder Stillingsdata meldes og registreres i NAV basert på (Lov om arbeidsmarkedstjenester § 7,2004). Ikke alle stillinger som blir meldt til NAV blir publisert på Arbeidsplassen. Du finner dokumentasjon av applikasjonsgrensesnittet på https://github.com/navikt/pam-public-feed',
                                           'title': 'Arbeidsplassen',
                                           'format': 'API',
                                           'category': 'API',
                                           'provenance': 'API',
                                           'master': 'NAV',
                                           'purpose': [''],
                                           'legalbasis': [],
                                           'pii': ['Persondata'],
                                           'issued': '2021-01-06T12:44:20.927866',
                                           'modified': '2021-01-06T12:44:20.927867',
                                           'created': '2021-01-06T12:44:20.927869',
                                           'distribution': None,
                                           'keywords': ['api'],
                                           'theme': ['API'],
                                           'accessRights': 'public',
                                           'publisher': {'name': 'NAV'},
                                           'spatial': 'Norge',
                                           'url': ['url'],
                                           'content': {'name': 'Arbeidsplassen',
                                                       'description': 'Stillingssøk på Arbeidsplassen inneholder en oversikt over de fleste aktive ledige stillinger. Stillingssøket inneholder både stillinger som er registrert direkte hos NAV samt hentet inn fra en rekke nettsteder Stillingsdata meldes og registreres i NAV basert på (Lov om arbeidsmarkedstjenester § 7,2004). Ikke alle stillinger som blir meldt til NAV blir publisert på Arbeidsplassen. Du finner dokumentasjon av applikasjonsgrensesnittet på https://github.com/navikt/pam-public-feed',
                                                       'app': 'pam-public-feed',
                                                       'swagger': 'https://arbeidsplassen.nav.no/public-feed/swagger',
                                                       'type': 'api',
                                                       'url': 'https://arbeidsplassen.nav.no/public-feed/api/v1',
                                                       'valid_to': ''}}}]}}
