API_JSON = {"hits": {"hits": [{'_id': 'API.DatakatalogAPI',
                               '_index': 'odata_v4',
                               '_score': 4.5781417,
                               '_source': {'accessRights': 'public',
                                           'category': 'API',
                                           'content': {'app': 'dataverk-api',
                                                       'description': 'Datakatalog api for s3 og elastic '
                                                                      'search',
                                                       'name': 'Datakatalog API',
                                                       'swagger': 'https://data.nav.no/api/swagger/ui',
                                                       'type': 'api',
                                                       'url': 'https://data.nav.no/api'},
                                           'created': '2020-09-07T13:00:56.200881',
                                           'description': 'Datakatalog api for s3 og elastic search',
                                           'distribution': None,
                                           'format': 'API',
                                           'id': 'API.DatakatalogAPI',
                                           'issued': '2020-09-07T13:00:56.200878',
                                           'keywords': ['api'],
                                           'legalbasis': [],
                                           'master': 'NAV',
                                           'modified': '2020-09-07T13:00:56.200879',
                                           'pii': ['Persondata'],
                                           'provenance': 'API',
                                           'publisher': {'name': 'NAV'},
                                           'purpose': [''],
                                           'spatial': 'Norge',
                                           'suggest': 'Datakatalog API',
                                           'theme': ['API'],
                                           'title': 'Datakatalog API',
                                           'type': 'api',
                                           'url': ['url']},
                               '_type': '_doc'}]}}
