TERM_JSON = {'took': 27,
             'timed_out': False,
             '_shards': {'total': 5, 'successful': 5, 'skipped': 0, 'failed': 0},
             'hits': {'total': 1,
                      'max_score': 0.03325722,
                      'hits': [{'_index': 'odata_v2',
                                '_type': '_doc',
                                '_id': 'BEGREP-1694',
                                '_score': 0.03325722,
                                '_source': {'id': 'BEGREP-1694',
                                            'versionInfo': '0.0.1',
                                            'versionNotes': [],
                                            'type': 'godkjent_begrep',
                                            'format': 'godkjent_begrep',
                                            'suggest': 'Business Use Case (EESSI) Et bruksområde av Use Case som beskriver typiske forretningsoperasjoner mellom en aktør på utsiden og en organisasjon.',
                                            'description': 'Et bruksområde av Use Case som beskriver typiske forretningsoperasjoner mellom en aktør på utsiden og en organisasjon.',
                                            'title': 'Business Use Case (EESSI)',
                                            'license': {'name': 'CC BY 4.0',
                                                        'url': 'http://creativecommons.org/licenses/by/4.0/deed.no'},
                                            'language': 'Norsk',
                                            'accrualPeriodicity': '',
                                            'temporal': [],
                                            'category': '',
                                            'status': 'Godkjent begrep',
                                            'rights': ['Open'],
                                            'byteSize': [],
                                            'provenance': 'NAV',
                                            'issued': '2020-05-26T08:33:22.333055',
                                            'modified': '2020-05-05T12:37:57.000+0200',
                                            'distribution': [],
                                            'keyword': [],
                                            'term': 'Business Use Case (EESSI)',
                                            'theme': ['Begreper'],
                                            'accessRights': ['public'],
                                            'accessRightsComment': '',
                                            'publisher': {'name': 'Arbeids- og velferdsetaten (NAV)',
                                                          'publisher_url': 'https://www.nav.no'},
                                            'spatial': [],
                                            'content': {'type': 'term',
                                                        'term': 'Business Use Case (EESSI)',
                                                        'status': 'Godkjent begrep',
                                                        'begrepsforklaring': 'Business Use Case viser samhandling mellom aktører og forretningsprosesser, og trenger ikke inneholde referanser til teknologi. \r\n\r\nForkortelsen BUC inngår i  forkortelses-stammespråket i [EESSI](https://dataverk.nav.no/begrep/BEGREP-1618) som betegnelse på modeller for meldingsflyten mellom aktører i en saksbehandlingsprosess.',
                                                        'definisjon': 'Et bruksområde av [Use Case](https://dataverk.nav.no/begrep/BEGREP-1850) som beskriver typiske forretningsoperasjoner mellom en [aktør](https://dataverk.nav.no/begrep/BEGREP-297) på utsiden og en organisasjon.',
                                                        'oppdatert': '2020-05-05T12:37:57.000+0200',
                                                        'kilde': 'EESSI Architecture Overview Document',
                                                        'komponenter': [
                                                            {'self': 'https://source.no/',
                                                             'id': '21970',
                                                             'name': 'EESSI',
                                                             'description': 'Begreper som tilhører fagområdet EESSI'}],
                                                        'relasjoner': [{'id': '369830',
                                                                        'self': 'https://source.no/',
                                                                        'type': {'id': '10281',
                                                                                 'name': '81. Homograf',
                                                                                 'inward': 'er homograf til',
                                                                                 'outward': 'er homograf til',
                                                                                 'self': 'https://source.no/'},
                                                                        'outwardIssue': {'id': '505263',
                                                                                         'key': 'BEGREP-1909',
                                                                                         'self': 'https://source.no/',
                                                                                         'fields': {
                                                                                             'summary': 'Business Use Case',
                                                                                             'status': {
                                                                                                 'self': 'https://source.no/',
                                                                                                 'description': '',
                                                                                                 'iconUrl': 'https://source.no/',
                                                                                                 'name': 'Utkast',
                                                                                                 'id': '10122',
                                                                                                 'statusCategory': {
                                                                                                     'self': 'https://source.no/',
                                                                                                     'id': 4,
                                                                                                     'key': 'indeterminate',
                                                                                                     'colorName': 'yellow',
                                                                                                     'name': 'Under arbeid'}},
                                                                                             'issuetype': {
                                                                                                 'self': 'https://source.no/',
                                                                                                 'id': '47',
                                                                                                 'description': '',
                                                                                                 'iconUrl': 'https://source.no/',
                                                                                                 'name': 'Begrep',
                                                                                                 'subtask': False}}}},
                                                                       {'id': '369831',
                                                                        'self': 'https://source.no/',
                                                                        'type': {'id': '10282',
                                                                                 'name': '82. Betydning',
                                                                                 'inward': 'utvidet betydning',
                                                                                 'outward': 'innsnevret betydning',
                                                                                 'self': 'https://source.no/'},
                                                                        'inwardIssue': {'id': '505263',
                                                                                        'key': 'BEGREP-1909',
                                                                                        'self': 'https://source.no/',
                                                                                        'fields': {
                                                                                            'summary': 'Business Use Case',
                                                                                            'status': {
                                                                                                'self': 'https://source.no/rest/api/2/status/10122',
                                                                                                'description': '',
                                                                                                'iconUrl': 'https://source.no/images/icons/statuses/document.png',
                                                                                                'name': 'Utkast',
                                                                                                'id': '10122',
                                                                                                'statusCategory': {
                                                                                                    'self': 'https://source.no/rest/api/2/statuscategory/4',
                                                                                                    'id': 4,
                                                                                                    'key': 'indeterminate',
                                                                                                    'colorName': 'yellow',
                                                                                                    'name': 'Under arbeid'}},
                                                                                            'issuetype': {
                                                                                                'self': 'https://source.no/',
                                                                                                'id': '47',
                                                                                                'description': '',
                                                                                                'iconUrl': 'https://source.no/',
                                                                                                'name': 'Begrep',
                                                                                                'subtask': False}}}}],
                                                        'clean_komponenter': 'Ytelsesavdelingen',
                                                        'eksempel': '- Samhandling/informasjonsutveksling  for å avgjøre krav om arbeidsledighetsytelse\r\n- Samhandling/informasjonsutveksling  for å fastsette bosted etter EU-forordning 883/2004',
                                                        'offentlig_tilgjengelig': 'Ja',
                                                        'forhold_til_kilde': 'basert på kilde',
                                                        'alternativ_navn': 'Bruksmønster, Forretningsbruksmønster, Samhandlingsmønster, BUC',
                                                        'clean_definisjon': 'Et bruksområde av Use Case som beskriver typiske forretningsoperasjoner mellom en aktør på utsiden og en organisasjon.',
                                                        'html_definisjon': '<p>Et bruksområde av Use Case som beskriver typiske forretningsoperasjoner mellom en aktør på utsiden og en organisasjon.</p>',
                                                        'clean_begrepsforklaring': 'Business Use Case viser samhandling mellom aktører og forretningsprosesser, og trenger ikke inneholde referanser til teknologi. \r\n\r\nForkortelsen BUC inngår i  forkortelses-stammespråket i EESSI som betegnelse på modeller for meldingsflyten mellom aktører i en saksbehandlingsprosess.',
                                                        'clean_eksempel': '- Samhandling/informasjonsutveksling  for å avgjøre krav om arbeidsledighetsytelse\r\n- Samhandling/informasjonsutveksling  for å fastsette bosted etter EU-forordning 883/2004',
                                                        'clean_kilde': 'EESSI Architecture Overview Document',
                                                        'html_kilde': '<p>EESSI Architecture Overview Document</p>',
                                                        'id': 'BEGREP-1694'}}}]
                      }
             }
