name: Deploy prod

on:
  release:
    types: [published]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  deploy-prod:
    name: deploy to nais prod-gcp cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: nais/deploy/actions/deploy@v1
      env:
        CLUSTER: prod-gcp
        RESOURCE: .nais/nais.yaml
        VARS: .nais/config-prod-gcp.json
